/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "!./node_modules/",
    "!./dist/",
    "!./public/",
    "./index.html",
    "./*.{html,jsx,js}",
    "./**/*.{js,jsx,html}",
    "./**/**/*.{js,jsx,html}",
  ],
  theme: {},
  plugins: [require("daisyui")],
  // Default themes are *NOT COMMENTED*. Only *UNCOMMENT* those you *NEED*
  daisyui: {
    themes: [
      // "acid",
      // "aqua",
      // "autumn",
      // "black",
      // "bumblebee",
      // "business",
      // "cmyk",
      // "coffee",
      // "corporate",
      // "cupcake",
      // "cyberpunk",
      "dark",
      // "dim",
      // "dracula",
      // "emerald",
      // "fantasy",
      // "forest",
      // "garden",
      // "halloween",
      // "lemonade",
      "light",
      // "lofi",
      // "luxury",
      // "night",
      // "nord",
      // "pastel",
      // "retro",
      // "sunset",
      // "synthwave",
      // "valentine",
      // "winter",
      // "wireframe",
    ],
  },
}
